### ISSUE TITLE
Null parameter given during cache warm up

### ISSUE THREAD

**Issue by JorickPepin** [Tiime-Software/TiimeNewRelicBundle#8]
Hello, thanks a lot for providing an updated fork!

I have the following error during cache warm up, because of the `ansi` parameter being set to null by default:
```php
Tiime\NewRelicBundle\NewRelic\BlackholeInteractor::addCustomParameter():
 Argument #2 ($value) must be of type string|int|float|bool, null given, called
 in /var/www/vendor/tiime/newrelic-bundle/src/Listener/CommandListener.php  
 on line 68 
```
This is fixed by https://github.com/Tiime-Software/TiimeNewRelicBundle/pull/7 but the PR has not been included in the 1.0 release, could you please make a new one?

**Comment by rflavien** [comment]
Hello, thanks for the feedback, the release is done https://github.com/Tiime-Software/TiimeNewRelicBundle/releases/tag/v1.0.1
